### ISSUE TITLE
Doesn`t install by Composer on Pimcore 6.1.0

### ISSUE THREAD

**Issue by vmalyk** [pimcore/customer-data-framework#119]
On Installation composer require pimcore/customer-management-framework-bundle:~2.1.0 I got conflicts:

  Problem 1
    - Installation request for pimcore/customer-management-framework-bundle ~2.1.0 -> satisfiable by pimcore/customer-management-framework-bundle[v2.1.0].
    - pimcore/customer-management-framework-bundle v2.1.0 requires hwi/oauth-bundle ~0.6.2 -> satisfiable by hwi/oauth-bundle[0.6.2, 0.6.3].
    - Conclusion: don't install hwi/oauth-bundle 0.6.3
    - hwi/oauth-bundle 0.6.2 requires php-http/client-implementation ^1.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1].
    - php-http/guzzle6-adapter v2.0.0 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
    - php-http/guzzle6-adapter v2.0.1 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
    - Conclusion: don't install php-http/httplug v2.0.0

**Comment by das-peter** [comment]
Same here, issue is the `hwi/oauth-bundle` which doesn't have an official release that supports `guzzle6-adapter` 2.x and this package requires `php-http/httplug-bundle:~1.10.0` which doesn't support `guzzle6-adapter` 2.x  either.
So I think to get this working we need to fix the dependency to `php-http/httplug-bundle:~1.12` and maybe we need to use a dev dependency to `hwi/oauth-bundle` as `hwi/oauth-bundle` dev is up to date: https://github.com/hwi/HWIOAuthBundle/commit/14e0dbb0fa6ef5c4108566fb5cda553d5e382633#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R121

I've created a fork of this bundle - https://github.com/das-peter/customer-data-framework/tree/dev-dependency-fix-httplug-bundle
To use the fork you need to add following to your `composer.json`:
```
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/das-peter/customer-data-framework.git"
    }
  ],
```
Then following update should work: 
`composer require --update-with-all-dependencies "pimcore/pimcore:6.1.1" "pimcore/customer-management-framework-bundle:dev-dependency-fix-httplug-bundle" "hwi/oauth-bundle:dev-master#4a479bd50d9e3485b10084a4f84f154c4193be59" "php-http/guzzle6-adapter:2.0.1"`

This will fetch the branch from the fork of `customer-management-framework-bundle` as well as a fixed commit from `hwi/oauth-bundle`. Don't forget to remove the `repositories` definition for the fork again and switch to an official version once this issue is fixed.

This is all quite a bit convoluted :| For me the dev dependency to `hwi/oauth-bundle` feels in particular unclean as it is on a new branch (master instead 6.x) which could indicate trouble - however the latest release of `hwi/oauth-bundle` (0.6.3) must have created using the master branch. That sounds like the master isn't that out of line.

We might want to encourage `hwi/oauth-bundle` to provide a new release with the up to date dependencies on order to get rid of all the weirdness once we've confirmed that everything works.
