### ISSUE TITLE
JSON datatype instead of dynamic columns

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/customer-data-framework#58]
Currently MariaDB is needed to install this plugin.
Meanwhile most RDBMS (MySQL 5.7, Postgres 9.3, AWS Aurora) support a JSON datatype. What do you think of using this instead of dynamic columns?

**Comment by fashxp** [comment]
we would love to see additional implementations for the activity store - mysql JSON datatype seems to be a reasonable choice. 

It should be quite easy since just the interface `ActivityStoreEntryInterface` and configure the correct implementation as `cmf.activity_store` in the container. 

Maybe we need to add an additional hook into the installer in order to enable additional table creations etc. while installing the framework.
