### ISSUE TITLE
Access control for documents

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/customer-data-framework#81]
We would like to have documents which are only accessible for certain target groups. At the moment it is only possible to customize a document based on a target group but you cannot make a document accessible only for certain target groups. Or did we miss something?

We imagine a document setting to specify which target groups have access to the document. If the current user's target group does not have access, the document is neither shown in the navigation nor is it accessible via URL.

If this is not possible at the moment, we could invest some time to implement it but wanted to discuss this feature beforehand if you think it is desirable.

**Comment by fashxp** [comment]
are you talking of target groups in terms of logged-in users that belong to certain target groups? if so, have a look at https://github.com/pimcore/frontend-permission-toolkit

if you are talking of anonymous visitors that should see or not see certain documents based on their cookie assigned target groups, this might be a bit more tricky. but since you can access the target groups of the current visitor via the visitor info, it could be a similar approach as with the frontend permission toolkit. but there is no finished implementation for that yet.

**Comment by BlackbitNeueMedien** [comment]
Ah, exactly what we are looking for. Thank you!
